name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read   # permitir leitura do repositório
  pages: write     # permitir publicar no GitHub Pages
  id-token: write  # necessário para OIDC (mesmo que não usado aqui)

jobs:

  build:
    name: Build the React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies & build
        working-directory: ./app
        run: |
          npm ci
          npm run build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # mantém GITHUB_TOKEN para o push

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build
          force_orphan: true
