name: Deploy React App

# Workflow acionado em push na branch main
on:
  push:
    branches: [main]

jobs:
  build:
    # Executa em ambiente Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v3

      # Instala Node.js versão 20
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instala dependências na pasta app
      - name: Install dependencies
        working-directory: app
        run: npm ci

      # Executa lint se existir script
      - name: Run lint
        working-directory: app
        run: npm run lint --if-present

      # Executa testes sem watch
      - name: Run tests
        working-directory: app
        run: npm run test -- --watchAll=false

      # Gera build de produção
      - name: Build project
        working-directory: app
        run: npm run build

      # Faz upload do build como artefato
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: app/build

  deploy:
    # Executa apenas após job build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Baixa artefato gerado no job build
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: app/build

      # Publica o conteúdo de app/build no GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build
